# Generated by Django 4.1.7 on 2023-03-01 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('roomno', models.IntegerField(unique=True)),
                ('roomtype', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('bookedtime', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 6, 18, 29, 755635))),
            ],
        ),
    ]
