# Generated by Django 4.1.7 on 2023-03-01 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeny', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000)),
            ],
        ),
        migrations.AlterField(
            model_name='hoteldata',
            name='bookedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 22, 54, 54, 191695)),
        ),
    ]
