# Generated by Django 4.1.7 on 2023-03-01 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_moneysystem_alter_hoteldata_bookedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldata',
            name='bookedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 23, 32, 6, 731723)),
        ),
        migrations.AlterField(
            model_name='moneysystem',
            name='moeny',
            field=models.FloatField(),
        ),
    ]
