# Generated by Django 4.1.7 on 2023-03-01 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hoteldata_bookedtime_alter_moneysystem_moeny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneysystem',
            old_name='moeny',
            new_name='money',
        ),
        migrations.AlterField(
            model_name='hoteldata',
            name='bookedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 23, 33, 50, 646610)),
        ),
    ]
