# Generated by Django 4.1.7 on 2023-03-01 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_moeny_moneysystem_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldata',
            name='bookedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 2, 1, 2, 34, 870493)),
        ),
        migrations.AlterField(
            model_name='hoteldata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hoteldata',
            name='roomno',
            field=models.IntegerField(),
        ),
    ]
